# Generated by Django 3.0.8 on 2020-08-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200811_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='owner',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='number_watchlist',
            field=models.IntegerField(),
        ),
    ]
