# Generated by Django 3.0.8 on 2020-08-11 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200811_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='owner_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
