# Generated by Django 3.1 on 2020-08-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200814_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='number_watchlist',
        ),
    ]
