# Generated by Django 3.1 on 2020-08-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_watchlist_number_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='opened',
            field=models.BooleanField(default='True'),
        ),
    ]
