# Generated by Django 3.1 on 2020-08-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listing_opened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='opened',
            field=models.BooleanField(default=True),
        ),
    ]
