# Generated by Django 3.1 on 2020-08-15 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_remove_watchlist_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='opened',
            new_name='status',
        ),
    ]
