# Generated by Django 3.0.8 on 2020-08-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_watchlist_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='item',
        ),
    ]
