# Generated by Django 3.0.8 on 2020-08-22 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_auto_20200822_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='ended',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='started',
        ),
        migrations.AddField(
            model_name='auction',
            name='date_placed',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='auction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
