# Generated by Django 3.0.8 on 2020-08-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_auto_20200822_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='number_bids',
        ),
    ]
